I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script2.rpy", line 199, in script
    play sound h1
  File "renpy/common/000statements.rpy", line 300, in execute_play_sound
    renpy.sound.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "game/script2.rpy", line 199, in <module>
    play sound h1
NameError: name 'h1' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script2.rpy", line 199, in script
    play sound h1
  File "/Volumes/renpy-8.1.3-sdk/renpy-8.1.3-sdk/renpy/ast.py", line 2259, in execute
    self.call("execute")
  File "/Volumes/renpy-8.1.3-sdk/renpy-8.1.3-sdk/renpy/ast.py", line 2241, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "/Volumes/renpy-8.1.3-sdk/renpy-8.1.3-sdk/renpy/statements.py", line 342, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 300, in execute_play_sound
    renpy.sound.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "/Volumes/renpy-8.1.3-sdk/renpy-8.1.3-sdk/renpy/python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Volumes/renpy-8.1.3-sdk/renpy-8.1.3-sdk/renpy/python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script2.rpy", line 199, in <module>
    play sound h1
NameError: name 'h1' is not defined

macOS-14.2.1-arm64-arm-64bit arm64
Ren'Py 8.1.3.23091805
Transition of Instances 1.0
Fri Jan  5 15:45:49 2024
